baseURL = "/"
languageCode = "en-us"
theme = "Gabriel Jones"
themesDir = "themes"
title = "Gabriel Jones"
paginate = 3
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]
  google_analytics_id = ""
  twitter_handle = "@gabrieljones"
  showAuthorOnHomepage = true
  showAuthorOnPosts = true
  showPostsOnHomepage = false
  addDot = true
  addFrame = true
  highlightColor = '#ff1616'

# markdown config settings https://gohugo.io/getting-started/configuration-markup/#goldmark
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false

[menu]

  [[menu.main]]
    identifier = 'home'
    name = 'Home'
    url = '/'
    weight = 1
    pre = "<i class='fa fa-home'></i>" # opzionale: icona prima del testo

  [[menu.main]]
    identifier = 'about'
    name = 'Chi sono'
    url = '/about/'
    weight = 2

  [[menu.main]]
    identifier = 'services'
    name = 'Servizi'
    url = '/services/'
    weight = 3

    # figli (submenu)
    [[menu.main]]
      parent = 'services'
      identifier = 'web'
      name = 'Sviluppo Web'
      url = '/services/web/'
      weight = 1

    [[menu.main]]
      parent = 'services'
      identifier = 'seo'
      name = 'SEO'
      url = '/services/seo/'
      weight = 2

  [[menu.main]]
    identifier = 'contact'
    name = 'Contatti'
    url = '/contact/'
    weight = 4

